server:
  servlet:
    context-path: "${SERVER_CONTEXT_PATH}"
  port: "${SERVER_PORT}"

spring:
  datasource:
    username: "${DATASOURCE_USERNAME}"
    password: "${DATASOURCE_PASSWORD}"
    url: "jdbc:mysql://${DATASOURCE_HOST}:${DATASOURCE_MYSQL_PORT}/${DATASOURCE_DATABASE}?serverTimezone=UTC&useUnicode=true@characterEncoding=utf-8"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        ddl-auto: none
    show-sql: "${JPA_SHOW_SQL}"


predefinedDateRange:
  priceResult:
    pageSize: 10


aws:
  sqs:
    stockPriceQueue : "${AWS_SQS_NAME}"
  s3:
    bucketName: "${AWS_S3_BUCKET_NAME}"
